[project]
name = "code-chat"
version = "0.1.0"
readme = "README.md"
authors = [
    { name = "Tetsuya Higashi", email = "996846+sluchin@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "code-chat-cli",
]

[project.scripts]
code-chat = "code_chat_cli.chat:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["packages/code-chat-cli/src/code_chat_cli"]

[tool.uv.sources]
code-chat-cli = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[dependency-groups]
dev = [
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
addopts = [
    "--cov=packages/code-chat-cli/src/code_chat_cli",
    "--cov=packages/code-chat-rag/src/code_chat_rag",
    "--cov-report=term-missing",
]
testpaths = ["tests"]
pythonpath = [
    "packages/code-chat-cli/src",
    "packages/code-chat-rag/src",
]
filterwarnings = [
    "ignore::DeprecationWarning",
]

[tool.pylint.master]
ignore-paths = [
    "^docs/.*",
    "^.venv/.*",
    "^build/.*",
    "^dist/.*",
]
